---
  - name: Apt install CLUES2 requirements in Deb system
    apt: pkg=unzip,git,wget update_cache=yes

  - name: Apt install pip3 in Deb
    apt: pkg=python3-pip,python3-setuptools
    when: ansible_python_version is version('3', '>=')

  - name: Apt install pip3 in Deb
    apt: pkg=python3-pip,python3-setuptools
    when: ansible_python_version is version('3', '>=')

  - name: Apt install pip2 in Deb
    apt: pkg=python-pip,python-setuptools,python-sqlite
    when: ansible_python_version is version('3', '<')
