- name: Set SBATCH_BINARY fact
  set_fact:
    SBATCH_BINARY: "{{item}}"
  with_first_found:
    - files:
      - "/usr/bin/sbatch"
      - "/usr/local/bin/sbatch"

- name: Set SCONTROL_BIN fact
  set_fact:
    SCONTROL_BIN: "{{item}}"
  with_first_found:
    - files:
      - "/usr/bin/scontrol"
      - "/usr/local/bin/scontrol"

- name: Set SBATCH_BACKUP fact
  set_fact:
    SBATCH_BACKUP: "{{SBATCH_BINARY}}.o"

- name: Set CLUES_SLURM_WRAPPER fact
  set_fact:
    CLUES_SLURM_WRAPPER: "{{item}}"
  with_first_found:
    - files:
      - "/usr/bin/clues-slurm-wrapper"
      - "/usr/local/bin/clues-slurm-wrapper"

- name: Start SLURM service
  command: slurmctld

- name: Reconfigure SLURM
  command: scontrol reconfig

- name: Set SLURM as CLUES2 LRMS
  ini_file: dest=/etc/clues2/clues2.cfg section=general option=LRMS_CLASS value=cluesplugins.slurm
  notify: restart cluesd

- name: Create SLURM plugin configuration file for CLUES2
  get_url:
    url: https://raw.githubusercontent.com/grycap/clues/refs/heads/master/etc/conf.d/plugin-slurm.cfg-example
    dest: /etc/clues2/conf.d/plugin-slurm.cfg
    force: no
    mode: '0644'
  notify: restart cluesd

- name: Set SLURM_SERVER value
  ini_file: dest=/etc/clues2/conf.d/plugin-slurm.cfg section=SLURM option=SLURM_SERVER value=slurmserver
  notify: restart cluesd

- name: Set SLURM specific config for CentOS
  ini_file: dest=/etc/clues2/conf.d/plugin-slurm.cfg section=SLURM option={{ item.option }} value="{{ item.value }}"
  notify: restart cluesd
  with_items:
    - { option: 'SLURM_PARTITION_COMMAND', value: '{{SCONTROL_BIN}} -o show partitions' }
    - { option: 'SLURM_NODES_COMMAND', value: '{{SCONTROL_BIN}} -o show nodes' }
    - { option: 'SLURM_JOBS_COMMAND', value: '{{SCONTROL_BIN}} -o show jobs' }

- name: Create sbatch script backup
  copy: src={{SBATCH_BINARY}} dest={{SBATCH_BACKUP}} mode=755 force=no

- name: Replace sbatch script with clues-slurm wrapper
  copy: src={{CLUES_SLURM_WRAPPER}} dest={{SBATCH_BINARY}}
