---
- name: Converge
  hosts: all
  tasks:
 
    - name: Link python 3 or 2 in case is needed
      shell: ls /usr/bin/python || { ls /usr/bin/python3 && ln -s /usr/bin/python3 /usr/bin/python; } || { ls /usr/bin/python2 && ln -s /usr/bin/python2 /usr/bin/python; }
      changed_when: false

    - name: "Include grycap.clues"
      include_role:
        name: "ansible-role-clues"
      vars:
        clues_queue_system: kubernetes
        auth: "id = test; proxy = ----proxy----"

    - name: test
      command: clues status
      changed_when: false